# Generated by Django 3.0.8 on 2020-08-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('psw', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=32)),
                ('time_con', models.CharField(max_length=64)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Account', to_field='username')),
            ],
        ),
    ]
