# Generated by Django 3.1.7 on 2021-03-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(null=True)),
                ('output', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='username',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
